ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
 
Vagrant.configure("2") do |config|

    # binds current directory on the host to the directory '/usr/local/src' on the docker image run.
    # may be used docker volume binding, but we cannot use "." there
    config.vm.synced_folder ".", "/usr/local/src"
 
    config.vm.define "vertxdev-src" do |a|
        a.vm.provider "docker" do |d|
            d.build_dir = "."
            d.build_args = ["-t=vertxdev"]
            d.ports = ["8080:8080"]
            d.name = "vertxdev-src"
            d.remains_running = true
            d.cmd = ["vertx", "run", "vertx-examples/src/raw/java/httphelloworld/HelloWorldServer.java"]
            d.vagrant_machine = "dockerhost"
            d.vagrant_vagrantfile = "./DockerHostVagrantfile"
        end
    end
 
end