Vagrant.configure(2) do |config|
  config.vm.network "public_network"
  config.vm.network :forwarded_port, guest: 9100, host: 9100
  config.vm.network :forwarded_port, guest: 9101, host: 9101
  config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.provision "shell",
      inline: "curl -sSL http://stackstorm.com/install.sh | sudo su"
end