ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
 
Vagrant.configure("2") do |config|

 config.vm.synced_folder ".", "/usr/share/elasticsearch/data"

  config.vm.define "elasticsearch-test-server" do |a|
    a.vm.provider "docker" do |d|
      d.build_dir = "."
      d.build_args = ["-t=elastic-search-test-server"]
      d.ports = ["9200:9200"]
      d.name = "elasticsearch-test-server"
      d.remains_running = true
      d.vagrant_machine = "dockerhost-elasticsearch"
      d.vagrant_vagrantfile = "./DockerHostVagrantfile"
    end
  end

end