CFG_MEMSIZE = "1000"
CFG_IP = "10.211.54.10"

Vagrant.configure(2) do |config|
  config.vm.define :cassandra do |c|
    c.vm.box = "hashicorp/precise64"
    c.vm.provider "vmware_fusion" do |v|
      v.vmx["memsize"] = CFG_MEMSIZE
    end
    c.vm.provider :virtualbox do |v|
      v.name = "cassandra"
      v.customize ["modifyvm", :id, "--memory", CFG_MEMSIZE]
    end
    c.vm.network :private_network, ip: CFG_IP
    c.vm.hostname = "cassandra"
    c.vm.provision :file do |f|
      f.source = "load_users.cql"
      f.destination = "/home/vagrant/data/load_users.cql"
    end
    c.vm.provision :file do |f|
      f.source = "sample_users.csv"
      f.destination = "/home/vagrant/data/sample_users.csv"
    end
    c.vm.provision :shell, path: "../install_cassandra.sh"
    c.vm.provision :shell, path: "../start_cassandra.sh", privileged: false
  end
end